// FILE: oh-my-pi.seed.generated.ts
// Purpose: Peak Code ChromeTheme seeds derived from the can1357/oh-my-pi theme collection.
// Layer: Web appearance generated catalog
// Generated by: scripts/generate-oh-my-pi-theme-seeds.ts --source <oh-my-pi checkout>
// Upstream: can1357/oh-my-pi@9b2a43514bfcfc0b9607ac9ac160115aec897f06 (MIT). Do not edit by hand.
// Exports: OH_MY_PI_CODE_THEME_OPTIONS and OH_MY_PI_THEME_SEEDS, merged into the catalog
// by ./theme.logic.ts.

import type { ChromeTheme, ThemeVariant } from "./theme.logic";

export const OH_MY_PI_CODE_THEME_OPTIONS = [
  { id: "omp-alabaster", label: "OMP Alabaster", variants: ["light"] },
  { id: "omp-amethyst", label: "OMP Amethyst", variants: ["dark"] },
  { id: "omp-anthracite", label: "OMP Anthracite", variants: ["dark"] },
  { id: "omp-basalt", label: "OMP Basalt", variants: ["dark"] },
  { id: "omp-birch", label: "OMP Birch", variants: ["light"] },
  { id: "omp-dark", label: "OMP Dark", variants: ["dark"] },
  { id: "omp-dark-abyss", label: "OMP Dark Abyss", variants: ["dark"] },
  { id: "omp-dark-arctic", label: "OMP Dark Arctic", variants: ["dark"] },
  { id: "omp-dark-aurora", label: "OMP Dark Aurora", variants: ["dark"] },
  { id: "omp-dark-catppuccin", label: "OMP Dark Catppuccin", variants: ["dark"] },
  { id: "omp-dark-cavern", label: "OMP Dark Cavern", variants: ["dark"] },
  { id: "omp-dark-copper", label: "OMP Dark Copper", variants: ["dark"] },
  { id: "omp-dark-cosmos", label: "OMP Dark Cosmos", variants: ["dark"] },
  { id: "omp-dark-cyberpunk", label: "OMP Dark Cyberpunk", variants: ["dark"] },
  { id: "omp-dark-dracula", label: "OMP Dark Dracula", variants: ["dark"] },
  { id: "omp-dark-eclipse", label: "OMP Dark Eclipse", variants: ["dark"] },
  { id: "omp-dark-ember", label: "OMP Dark Ember", variants: ["dark"] },
  { id: "omp-dark-equinox", label: "OMP Dark Equinox", variants: ["dark"] },
  { id: "omp-dark-forest", label: "OMP Dark Forest", variants: ["dark"] },
  { id: "omp-dark-github", label: "OMP Dark Github", variants: ["dark"] },
  { id: "omp-dark-gruvbox", label: "OMP Dark Gruvbox", variants: ["dark"] },
  { id: "omp-dark-lavender", label: "OMP Dark Lavender", variants: ["dark"] },
  { id: "omp-dark-lunar", label: "OMP Dark Lunar", variants: ["dark"] },
  { id: "omp-dark-midnight", label: "OMP Dark Midnight", variants: ["dark"] },
  { id: "omp-dark-monochrome", label: "OMP Dark Monochrome", variants: ["dark"] },
  { id: "omp-dark-monokai", label: "OMP Dark Monokai", variants: ["dark"] },
  { id: "omp-dark-nebula", label: "OMP Dark Nebula", variants: ["dark"] },
  { id: "omp-dark-nord", label: "OMP Dark Nord", variants: ["dark"] },
  { id: "omp-dark-ocean", label: "OMP Dark Ocean", variants: ["dark"] },
  { id: "omp-dark-one", label: "OMP Dark One", variants: ["dark"] },
  { id: "omp-dark-poimandres", label: "OMP Dark Poimandres", variants: ["dark"] },
  { id: "omp-dark-rainforest", label: "OMP Dark Rainforest", variants: ["dark"] },
  { id: "omp-dark-reef", label: "OMP Dark Reef", variants: ["dark"] },
  { id: "omp-dark-retro", label: "OMP Dark Retro", variants: ["dark"] },
  { id: "omp-dark-rose-pine", label: "OMP Dark Rose Pine", variants: ["dark"] },
  { id: "omp-dark-sakura", label: "OMP Dark Sakura", variants: ["dark"] },
  { id: "omp-dark-slate", label: "OMP Dark Slate", variants: ["dark"] },
  { id: "omp-dark-solarized", label: "OMP Dark Solarized", variants: ["dark"] },
  { id: "omp-dark-solstice", label: "OMP Dark Solstice", variants: ["dark"] },
  { id: "omp-dark-starfall", label: "OMP Dark Starfall", variants: ["dark"] },
  { id: "omp-dark-sunset", label: "OMP Dark Sunset", variants: ["dark"] },
  { id: "omp-dark-swamp", label: "OMP Dark Swamp", variants: ["dark"] },
  { id: "omp-dark-synthwave", label: "OMP Dark Synthwave", variants: ["dark"] },
  { id: "omp-dark-taiga", label: "OMP Dark Taiga", variants: ["dark"] },
  { id: "omp-dark-terminal", label: "OMP Dark Terminal", variants: ["dark"] },
  { id: "omp-dark-tokyo-night", label: "OMP Dark Tokyo Night", variants: ["dark"] },
  { id: "omp-dark-tundra", label: "OMP Dark Tundra", variants: ["dark"] },
  { id: "omp-dark-twilight", label: "OMP Dark Twilight", variants: ["dark"] },
  { id: "omp-dark-volcanic", label: "OMP Dark Volcanic", variants: ["dark"] },
  { id: "omp-graphite", label: "OMP Graphite", variants: ["dark"] },
  { id: "omp-light", label: "OMP Light", variants: ["light"] },
  { id: "omp-light-arctic", label: "OMP Light Arctic", variants: ["light"] },
  { id: "omp-light-aurora-day", label: "OMP Light Aurora Day", variants: ["light"] },
  { id: "omp-light-canyon", label: "OMP Light Canyon", variants: ["light"] },
  { id: "omp-light-catppuccin", label: "OMP Light Catppuccin", variants: ["light"] },
  { id: "omp-light-cirrus", label: "OMP Light Cirrus", variants: ["light"] },
  { id: "omp-light-coral", label: "OMP Light Coral", variants: ["light"] },
  { id: "omp-light-cyberpunk", label: "OMP Light Cyberpunk", variants: ["light"] },
  { id: "omp-light-dawn", label: "OMP Light Dawn", variants: ["light"] },
  { id: "omp-light-dunes", label: "OMP Light Dunes", variants: ["light"] },
  { id: "omp-light-eucalyptus", label: "OMP Light Eucalyptus", variants: ["light"] },
  { id: "omp-light-forest", label: "OMP Light Forest", variants: ["light"] },
  { id: "omp-light-frost", label: "OMP Light Frost", variants: ["light"] },
  { id: "omp-light-github", label: "OMP Light Github", variants: ["light"] },
  { id: "omp-light-glacier", label: "OMP Light Glacier", variants: ["light"] },
  { id: "omp-light-gruvbox", label: "OMP Light Gruvbox", variants: ["light"] },
  { id: "omp-light-haze", label: "OMP Light Haze", variants: ["light"] },
  { id: "omp-light-honeycomb", label: "OMP Light Honeycomb", variants: ["light"] },
  { id: "omp-light-lagoon", label: "OMP Light Lagoon", variants: ["light"] },
  { id: "omp-light-lavender", label: "OMP Light Lavender", variants: ["light"] },
  { id: "omp-light-meadow", label: "OMP Light Meadow", variants: ["light"] },
  { id: "omp-light-mint", label: "OMP Light Mint", variants: ["light"] },
  { id: "omp-light-monochrome", label: "OMP Light Monochrome", variants: ["light"] },
  { id: "omp-light-ocean", label: "OMP Light Ocean", variants: ["light"] },
  { id: "omp-light-one", label: "OMP Light One", variants: ["light"] },
  { id: "omp-light-opal", label: "OMP Light Opal", variants: ["light"] },
  { id: "omp-light-orchard", label: "OMP Light Orchard", variants: ["light"] },
  { id: "omp-light-paper", label: "OMP Light Paper", variants: ["light"] },
  { id: "omp-light-poimandres", label: "OMP Light Poimandres", variants: ["light"] },
  { id: "omp-light-prism", label: "OMP Light Prism", variants: ["light"] },
  { id: "omp-light-retro", label: "OMP Light Retro", variants: ["light"] },
  { id: "omp-light-sand", label: "OMP Light Sand", variants: ["light"] },
  { id: "omp-light-savanna", label: "OMP Light Savanna", variants: ["light"] },
  { id: "omp-light-solarized", label: "OMP Light Solarized", variants: ["light"] },
  { id: "omp-light-soleil", label: "OMP Light Soleil", variants: ["light"] },
  { id: "omp-light-sunset", label: "OMP Light Sunset", variants: ["light"] },
  { id: "omp-light-synthwave", label: "OMP Light Synthwave", variants: ["light"] },
  { id: "omp-light-tokyo-night", label: "OMP Light Tokyo Night", variants: ["light"] },
  { id: "omp-light-wetland", label: "OMP Light Wetland", variants: ["light"] },
  { id: "omp-light-zenith", label: "OMP Light Zenith", variants: ["light"] },
  { id: "omp-limestone", label: "OMP Limestone", variants: ["light"] },
  { id: "omp-mahogany", label: "OMP Mahogany", variants: ["dark"] },
  { id: "omp-marble", label: "OMP Marble", variants: ["light"] },
  { id: "omp-obsidian", label: "OMP Obsidian", variants: ["dark"] },
  { id: "omp-onyx", label: "OMP Onyx", variants: ["dark"] },
  { id: "omp-pearl", label: "OMP Pearl", variants: ["light"] },
  { id: "omp-porcelain", label: "OMP Porcelain", variants: ["light"] },
  { id: "omp-quartz", label: "OMP Quartz", variants: ["light"] },
  { id: "omp-sandstone", label: "OMP Sandstone", variants: ["light"] },
  { id: "omp-titanium", label: "OMP Titanium", variants: ["dark"] },
] as const satisfies readonly { id: string; label: string; variants: readonly ThemeVariant[] }[];

export const OH_MY_PI_THEME_SEEDS: Record<string, Partial<Record<ThemeVariant, ChromeTheme>>> = {
  "omp-alabaster": {
    light: {
      accent: "#505860",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#1a1c20",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#405840",
        diffRemoved: "#704040",
        skill: "#404850",
      },
      surface: "#fdfcfb",
    },
  },
  "omp-amethyst": {
    dark: {
      accent: "#b48eff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#c8a8e9",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#8eb897",
        diffRemoved: "#d96c75",
        skill: "#e5b4d4",
      },
      surface: "#140f18",
    },
  },
  "omp-anthracite": {
    dark: {
      accent: "#e8734a",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#a9b8cf",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#7fb069",
        diffRemoved: "#d9534f",
        skill: "#e8b089",
      },
      surface: "#121419",
    },
  },
  "omp-basalt": {
    dark: {
      accent: "#c45a3a",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e4e0d8",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6a9a6a",
        diffRemoved: "#b84a2c",
        skill: "#d97651",
      },
      surface: "#171613",
    },
  },
  "omp-birch": {
    light: {
      accent: "#608058",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#3a5048",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#7a9a70",
        diffRemoved: "#b85a50",
        skill: "#608058",
      },
      surface: "#f9f7f1",
    },
  },
  "omp-dark": {
    dark: {
      accent: "#febc38",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#9cdcfe",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#89d281",
        diffRemoved: "#fc3a4b",
        skill: "#e5c1ff",
      },
      surface: "#18181e",
    },
  },
  "omp-dark-abyss": {
    dark: {
      accent: "#3fd3ff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5aa4ff",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#35c28a",
        diffRemoved: "#e85b5b",
        skill: "#5aa4ff",
      },
      surface: "#05070b",
    },
  },
  "omp-dark-arctic": {
    dark: {
      accent: "#88c0d0",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#d8dee9",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a3be8c",
        diffRemoved: "#bf616a",
        skill: "#b48ead",
      },
      surface: "#1a1f2b",
    },
  },
  "omp-dark-aurora": {
    dark: {
      accent: "#bd00ff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#00e8c6",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ff9f",
        diffRemoved: "#ff0055",
        skill: "#bd00ff",
      },
      surface: "#0f0f1a",
    },
  },
  "omp-dark-catppuccin": {
    dark: {
      accent: "#fab387",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#cdd6f4",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a6e3a1",
        diffRemoved: "#f38ba8",
        skill: "#f5e0dc",
      },
      surface: "#1e1e2e",
    },
  },
  "omp-dark-cavern": {
    dark: {
      accent: "#5fb2d8",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#87c6e6",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6fb86a",
        diffRemoved: "#e06c75",
        skill: "#87c6e6",
      },
      surface: "#0b0d10",
    },
  },
  "omp-dark-copper": {
    dark: {
      accent: "#d08770",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#88c0d0",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a3be8c",
        diffRemoved: "#bf616a",
        skill: "#ebcb8b",
      },
      surface: "#242933",
    },
  },
  "omp-dark-cosmos": {
    dark: {
      accent: "#5b4bb7",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#7aa4ff",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#63cfa5",
        diffRemoved: "#e05a6a",
        skill: "#f4f1ff",
      },
      surface: "#07070d",
    },
  },
  "omp-dark-cyberpunk": {
    dark: {
      accent: "#ff007a",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#00bfff",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ffb3",
        diffRemoved: "#ff6f61",
        skill: "#8c1bff",
      },
      surface: "#091833",
    },
  },
  "omp-dark-dracula": {
    dark: {
      accent: "#bd93f9",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#8be9fd",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#50fa7b",
        diffRemoved: "#ff5555",
        skill: "#ff79c6",
      },
      surface: "#1e1f29",
    },
  },
  "omp-dark-eclipse": {
    dark: {
      accent: "#f5c542",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#8b8792",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#5fbf87",
        diffRemoved: "#d1495b",
        skill: "#cfc7b8",
      },
      surface: "#08070d",
    },
  },
  "omp-dark-ember": {
    dark: {
      accent: "#ff6f61",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#56b6c2",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#98c379",
        diffRemoved: "#e06c75",
        skill: "#e5c07b",
      },
      surface: "#21252b",
    },
  },
  "omp-dark-equinox": {
    dark: {
      accent: "#d6a55b",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5aa6b8",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6fbf8c",
        diffRemoved: "#d96a6a",
        skill: "#d7dbe0",
      },
      surface: "#0f1115",
    },
  },
  "omp-dark-forest": {
    dark: {
      accent: "#8fbc8f",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#9caf88",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4f7942",
        diffRemoved: "#c44c3c",
        skill: "#b8c5a0",
      },
      surface: "#0a120e",
    },
  },
  "omp-dark-github": {
    dark: {
      accent: "#58a6ff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#79c0ff",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#7ee787",
        diffRemoved: "#ff7b72",
        skill: "#79c0ff",
      },
      surface: "#010409",
    },
  },
  "omp-dark-gruvbox": {
    dark: {
      accent: "#fe8019",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#83a598",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#b8bb26",
        diffRemoved: "#fb4934",
        skill: "#d3869b",
      },
      surface: "#1d2021",
    },
  },
  "omp-dark-lavender": {
    dark: {
      accent: "#bd93f9",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#8be9fd",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#50fa7b",
        diffRemoved: "#ff5555",
        skill: "#ff79c6",
      },
      surface: "#1e1f29",
    },
  },
  "omp-dark-lunar": {
    dark: {
      accent: "#d6dbe3",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#a5c4e0",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6fc49b",
        diffRemoved: "#e06a6a",
        skill: "#d6dbe3",
      },
      surface: "#0a0c11",
    },
  },
  "omp-dark-midnight": {
    dark: {
      accent: "#2979ff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#00e5ff",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00e676",
        diffRemoved: "#ff1744",
        skill: "#00e5ff",
      },
      surface: "#000000",
    },
  },
  "omp-dark-monochrome": {
    dark: {
      accent: "#5fafaf",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#a5a5a5",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#558a55",
        diffRemoved: "#8a5555",
        skill: "#c0c0c0",
      },
      surface: "#0d0d0d",
    },
  },
  "omp-dark-monokai": {
    dark: {
      accent: "#fd971f",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#66d9ef",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a6e22e",
        diffRemoved: "#f92672",
        skill: "#ae81ff",
      },
      surface: "#1a1b17",
    },
  },
  "omp-dark-nebula": {
    dark: {
      accent: "#d66bd8",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#35b4c3",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#55c6a9",
        diffRemoved: "#e25a6a",
        skill: "#f2d7ff",
      },
      surface: "#0a0912",
    },
  },
  "omp-dark-nord": {
    dark: {
      accent: "#88c0d0",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#d8dee9",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a3be8c",
        diffRemoved: "#bf616a",
        skill: "#8fbcbb",
      },
      surface: "#2e3440",
    },
  },
  "omp-dark-ocean": {
    dark: {
      accent: "#ff8b6d",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#a7f0e8",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a7f0e8",
        diffRemoved: "#ff6f5e",
        skill: "#d4a5ff",
      },
      surface: "#050a1a",
    },
  },
  "omp-dark-one": {
    dark: {
      accent: "#e5c07b",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e06c75",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#98c379",
        diffRemoved: "#e06c75",
        skill: "#c678dd",
      },
      surface: "#1e2227",
    },
  },
  "omp-dark-poimandres": {
    dark: {
      accent: "#00ced1",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#a6accd",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ced1",
        diffRemoved: "#d0679d",
        skill: "#00ced1",
      },
      surface: "#1b1e28",
    },
  },
  "omp-dark-rainforest": {
    dark: {
      accent: "#b07ad9",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#a6b5aa",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6ebe78",
        diffRemoved: "#e07a6a",
        skill: "#b07ad9",
      },
      surface: "#080c0a",
    },
  },
  "omp-dark-reef": {
    dark: {
      accent: "#f07f6a",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#a6b8c7",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#58b39e",
        diffRemoved: "#e36d7c",
        skill: "#9b6ad4",
      },
      surface: "#070b10",
    },
  },
  "omp-dark-retro": {
    dark: {
      accent: "#ffc633",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#ffb000",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#88dd66",
        diffRemoved: "#ff6b6b",
        skill: "#ffc633",
      },
      surface: "#0a0a0a",
    },
  },
  "omp-dark-rose-pine": {
    dark: {
      accent: "#c4a7e7",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e0def4",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#9ccfd8",
        diffRemoved: "#eb6f92",
        skill: "#ebbcba",
      },
      surface: "#191724",
    },
  },
  "omp-dark-sakura": {
    dark: {
      accent: "#f06292",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#f48fb1",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a5d6a7",
        diffRemoved: "#ef9a9a",
        skill: "#f48fb1",
      },
      surface: "#1e181a",
    },
  },
  "omp-dark-slate": {
    dark: {
      accent: "#5e81ac",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#88c0d0",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a3be8c",
        diffRemoved: "#bf616a",
        skill: "#8fbcbb",
      },
      surface: "#2e3440",
    },
  },
  "omp-dark-solarized": {
    dark: {
      accent: "#268bd2",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#2aa198",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#859900",
        diffRemoved: "#dc322f",
        skill: "#2aa198",
      },
      surface: "#002b36",
    },
  },
  "omp-dark-solstice": {
    dark: {
      accent: "#5ac8a7",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#8fb2d9",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6bd6a2",
        diffRemoved: "#e06b6b",
        skill: "#c7d2e3",
      },
      surface: "#0a0f1c",
    },
  },
  "omp-dark-starfall": {
    dark: {
      accent: "#f2c45a",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#4f7fb2",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6cc98f",
        diffRemoved: "#e06464",
        skill: "#ffd98a",
      },
      surface: "#0a0c10",
    },
  },
  "omp-dark-sunset": {
    dark: {
      accent: "#ff9e4a",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#ff785e",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#89d281",
        diffRemoved: "#e44c1d",
        skill: "#fdbae7",
      },
      surface: "#120d18",
    },
  },
  "omp-dark-swamp": {
    dark: {
      accent: "#f2c35b",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#8ea59a",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4fc48f",
        diffRemoved: "#e06b6b",
        skill: "#5fb7a2",
      },
      surface: "#080d0c",
    },
  },
  "omp-dark-synthwave": {
    dark: {
      accent: "#ff2975",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#c0c0c8",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ffff",
        diffRemoved: "#ff2975",
        skill: "#ef9af2",
      },
      surface: "#0c0c0c",
    },
  },
  "omp-dark-taiga": {
    dark: {
      accent: "#7fb7c9",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e7efe7",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#8dbb7f",
        diffRemoved: "#e06a6a",
        skill: "#e7efe7",
      },
      surface: "#080c0a",
    },
  },
  "omp-dark-terminal": {
    dark: {
      accent: "#00ff00",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#00ffcc",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ff00",
        diffRemoved: "#ff0000",
        skill: "#00cc00",
      },
      surface: "#050505",
    },
  },
  "omp-dark-tokyo-night": {
    dark: {
      accent: "#bb9af7",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#c0caf5",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#9ece6a",
        diffRemoved: "#f7768e",
        skill: "#c0caf5",
      },
      surface: "#16161e",
    },
  },
  "omp-dark-tundra": {
    dark: {
      accent: "#66d1a1",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e3e9f0",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#5fb487",
        diffRemoved: "#d26b6b",
        skill: "#e3e9f0",
      },
      surface: "#080b0e",
    },
  },
  "omp-dark-twilight": {
    dark: {
      accent: "#e07a3f",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#4ba3a6",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6cc48f",
        diffRemoved: "#e05f63",
        skill: "#f2b36f",
      },
      surface: "#0f0e21",
    },
  },
  "omp-dark-volcanic": {
    dark: {
      accent: "#ff7a3d",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#6a8ca0",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4fc48a",
        diffRemoved: "#ff5c5c",
        skill: "#6a8ca0",
      },
      surface: "#0b0706",
    },
  },
  "omp-graphite": {
    dark: {
      accent: "#f0d050",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e8eaed",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#85a882",
        diffRemoved: "#d88989",
        skill: "#d4b896",
      },
      surface: "#1c1e22",
    },
  },
  "omp-light": {
    light: {
      accent: "#5a8080",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#001080",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#588458",
        diffRemoved: "#aa5555",
        skill: "#5a8080",
      },
      surface: "#f8f8f8",
    },
  },
  "omp-light-arctic": {
    light: {
      accent: "#8fbcbb",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#434c5e",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a3be8c",
        diffRemoved: "#bf616a",
        skill: "#8fbcbb",
      },
      surface: "#fafbfc",
    },
  },
  "omp-light-aurora-day": {
    light: {
      accent: "#8bcbb8",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#2f3b3a",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#3fa977",
        diffRemoved: "#c9545c",
        skill: "#2f3b3a",
      },
      surface: "#fbfcfd",
    },
  },
  "omp-light-canyon": {
    light: {
      accent: "#c96a3b",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#6e5a50",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#7f9a55",
        diffRemoved: "#b84b3d",
        skill: "#7f9a55",
      },
      surface: "#f8f1ea",
    },
  },
  "omp-light-catppuccin": {
    light: {
      accent: "#8839ef",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#4c4f69",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#40a02b",
        diffRemoved: "#d20f39",
        skill: "#179299",
      },
      surface: "#eff1f5",
    },
  },
  "omp-light-cirrus": {
    light: {
      accent: "#6aa3d7",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#2f3640",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#3ea574",
        diffRemoved: "#c84b4b",
        skill: "#2f3640",
      },
      surface: "#fafbfd",
    },
  },
  "omp-light-coral": {
    light: {
      accent: "#ff7043",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#546e7a",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#43a047",
        diffRemoved: "#e53935",
        skill: "#f4511e",
      },
      surface: "#fff8e1",
    },
  },
  "omp-light-cyberpunk": {
    light: {
      accent: "#ea00d9",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#1b1b2a",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ff9f",
        diffRemoved: "#ff007a",
        skill: "#ff007a",
      },
      surface: "#f5f5f7",
    },
  },
  "omp-light-dawn": {
    light: {
      accent: "#e29b6f",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#2d3440",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#3a9d70",
        diffRemoved: "#c94b4b",
        skill: "#8c5a2b",
      },
      surface: "#faf7f2",
    },
  },
  "omp-light-dunes": {
    light: {
      accent: "#7fb7b2",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#6c5644",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#7b8d3a",
        diffRemoved: "#c55a4d",
        skill: "#7fb7b2",
      },
      surface: "#fbf3e6",
    },
  },
  "omp-light-eucalyptus": {
    light: {
      accent: "#00897b",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#37474f",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#2e7d32",
        diffRemoved: "#c62828",
        skill: "#00796b",
      },
      surface: "#e0f7fa",
    },
  },
  "omp-light-forest": {
    light: {
      accent: "#4f7942",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#4f7942",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#9caf88",
        diffRemoved: "#be5103",
        skill: "#7e8c54",
      },
      surface: "#f5f3ed",
    },
  },
  "omp-light-frost": {
    light: {
      accent: "#03a9f4",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#1a1c1f",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4caf50",
        diffRemoved: "#f44336",
        skill: "#00bcd4",
      },
      surface: "#f1faff",
    },
  },
  "omp-light-github": {
    light: {
      accent: "#0969da",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#0550ae",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#1f883d",
        diffRemoved: "#cf222e",
        skill: "#0969da",
      },
      surface: "#f6f8fa",
    },
  },
  "omp-light-glacier": {
    light: {
      accent: "#3a7fb6",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#51626d",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#3e8f7a",
        diffRemoved: "#c45a55",
        skill: "#3e8f7a",
      },
      surface: "#f2f7fa",
    },
  },
  "omp-light-gruvbox": {
    light: {
      accent: "#689d6a",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#665c54",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#98971a",
        diffRemoved: "#cc241d",
        skill: "#689d6a",
      },
      surface: "#f9f5d7",
    },
  },
  "omp-light-haze": {
    light: {
      accent: "#f1c07a",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#3f3a33",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4b9a6b",
        diffRemoved: "#c95555",
        skill: "#8a5a2c",
      },
      surface: "#fbf6ee",
    },
  },
  "omp-light-honeycomb": {
    light: {
      accent: "#ffb300",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5d4037",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#388e3c",
        diffRemoved: "#d32f2f",
        skill: "#ff6f00",
      },
      surface: "#fffde7",
    },
  },
  "omp-light-lagoon": {
    light: {
      accent: "#2e7fa6",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5a7280",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#48a07c",
        diffRemoved: "#c45a55",
        skill: "#48a07c",
      },
      surface: "#eef6f8",
    },
  },
  "omp-light-lavender": {
    light: {
      accent: "#7e57c2",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#4527a0",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#43a047",
        diffRemoved: "#e53935",
        skill: "#673ab7",
      },
      surface: "#f3e5f5",
    },
  },
  "omp-light-meadow": {
    light: {
      accent: "#7a5bbf",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#556257",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#3f8f55",
        diffRemoved: "#c75b5b",
        skill: "#4f8b56",
      },
      surface: "#f3f7f1",
    },
  },
  "omp-light-mint": {
    light: {
      accent: "#00bfa5",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#555555",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#3cb371",
        diffRemoved: "#cd5c5c",
        skill: "#20b2aa",
      },
      surface: "#f0fdfa",
    },
  },
  "omp-light-monochrome": {
    light: {
      accent: "#3b82f6",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#404040",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#404040",
        diffRemoved: "#2d2d2d",
        skill: "#404040",
      },
      surface: "#fafafa",
    },
  },
  "omp-light-ocean": {
    light: {
      accent: "#378ad7",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5a6c7d",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#9bcbbb",
        diffRemoved: "#ff8a80",
        skill: "#7fdbdc",
      },
      surface: "#faf7f3",
    },
  },
  "omp-light-one": {
    light: {
      accent: "#0184bc",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#696c77",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#50a14f",
        diffRemoved: "#e45649",
        skill: "#0184bc",
      },
      surface: "#fafafa",
    },
  },
  "omp-light-opal": {
    light: {
      accent: "#9b8ad6",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#3c3942",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#46a17a",
        diffRemoved: "#c4565d",
        skill: "#d9a2b3",
      },
      surface: "#fbfaf9",
    },
  },
  "omp-light-orchard": {
    light: {
      accent: "#d97a9b",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#6d5f4c",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6fa84b",
        diffRemoved: "#b9473d",
        skill: "#6fa84b",
      },
      surface: "#f7f2e8",
    },
  },
  "omp-light-paper": {
    light: {
      accent: "#d19a66",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#4d4d4c",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#718c00",
        diffRemoved: "#c82829",
        skill: "#4271ae",
      },
      surface: "#f6f0e4",
    },
  },
  "omp-light-poimandres": {
    light: {
      accent: "#00ced1",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#506477",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ced1",
        diffRemoved: "#d0679d",
        skill: "#00ced1",
      },
      surface: "#e4f0fb",
    },
  },
  "omp-light-prism": {
    light: {
      accent: "#7c4dff",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#7c4dff",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#22c55e",
        diffRemoved: "#ef4444",
        skill: "#7c4dff",
      },
      surface: "#ffffff",
    },
  },
  "omp-light-retro": {
    light: {
      accent: "#ffbb00",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#2b2b2b",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#2d6632",
        diffRemoved: "#cc3333",
        skill: "#33cc66",
      },
      surface: "#f4f1e8",
    },
  },
  "omp-light-sand": {
    light: {
      accent: "#a1887f",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5d4037",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#2e7d32",
        diffRemoved: "#c62828",
        skill: "#8d6e63",
      },
      surface: "#fffaf0",
    },
  },
  "omp-light-savanna": {
    light: {
      accent: "#c98a3a",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#6e5c47",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6e8b3d",
        diffRemoved: "#c45a4f",
        skill: "#6e8b3d",
      },
      surface: "#f8f1e6",
    },
  },
  "omp-light-solarized": {
    light: {
      accent: "#2aa198",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#586e75",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#859900",
        diffRemoved: "#dc322f",
        skill: "#2aa198",
      },
      surface: "#fdf6e3",
    },
  },
  "omp-light-soleil": {
    light: {
      accent: "#c96a45",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#3a352f",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4f9b6c",
        diffRemoved: "#c94b4b",
        skill: "#8b4b2c",
      },
      surface: "#fbf7ef",
    },
  },
  "omp-light-sunset": {
    light: {
      accent: "#d4a259",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#1a1c1f",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#a87f5c",
        diffRemoved: "#c47a6a",
        skill: "#d4a259",
      },
      surface: "#fffcf5",
    },
  },
  "omp-light-synthwave": {
    light: {
      accent: "#ff71ce",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#7d5ba6",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#05ffa1",
        diffRemoved: "#ff2975",
        skill: "#b967ff",
      },
      surface: "#fef6ff",
    },
  },
  "omp-light-tokyo-night": {
    light: {
      accent: "#118c74",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#3760bf",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#587539",
        diffRemoved: "#f52a65",
        skill: "#007197",
      },
      surface: "#e1e2e7",
    },
  },
  "omp-light-wetland": {
    light: {
      accent: "#4b7aa8",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5b6e66",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4f9b6a",
        diffRemoved: "#c6564a",
        skill: "#4f9b6a",
      },
      surface: "#f1f5f3",
    },
  },
  "omp-light-zenith": {
    light: {
      accent: "#2a6fbe",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#2f343b",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#2f9d65",
        diffRemoved: "#c23b3b",
        skill: "#2aa3c2",
      },
      surface: "#ffffff",
    },
  },
  "omp-limestone": {
    light: {
      accent: "#a07840",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#504838",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#708060",
        diffRemoved: "#a85840",
        skill: "#a07840",
      },
      surface: "#f5f1e8",
    },
  },
  "omp-mahogany": {
    dark: {
      accent: "#c4a050",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#b5826f",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#6a7c5d",
        diffRemoved: "#9d4451",
        skill: "#d9b89c",
      },
      surface: "#181210",
    },
  },
  "omp-marble": {
    light: {
      accent: "#5a6878",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#5a6878",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#4a6741",
        diffRemoved: "#8b4049",
        skill: "#5a6878",
      },
      surface: "#f9f7f5",
    },
  },
  "omp-obsidian": {
    dark: {
      accent: "#9d7aff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e8e8ec",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#52e8a0",
        diffRemoved: "#ff5570",
        skill: "#9d7aff",
      },
      surface: "#0c0b0a",
    },
  },
  "omp-onyx": {
    dark: {
      accent: "#ffffff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#ffffff",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#40c977",
        diffRemoved: "#fa423e",
        skill: "#ffffff",
      },
      surface: "#181818",
    },
  },
  "omp-pearl": {
    light: {
      accent: "#b08090",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#504070",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#709070",
        diffRemoved: "#a06060",
        skill: "#b08090",
      },
      surface: "#f9f9fc",
    },
  },
  "omp-porcelain": {
    light: {
      accent: "#5070a0",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#1a2030",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#507050",
        diffRemoved: "#c04040",
        skill: "#907030",
      },
      surface: "#f8f9fc",
    },
  },
  "omp-quartz": {
    light: {
      accent: "#c07088",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#3a2830",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#88a088",
        diffRemoved: "#b85860",
        skill: "#c07088",
      },
      surface: "#fbf7f9",
    },
  },
  "omp-sandstone": {
    light: {
      accent: "#b86040",
      contrast: 45,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#544840",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#688058",
        diffRemoved: "#b86040",
        skill: "#b86040",
      },
      surface: "#f5ede3",
    },
  },
  "omp-titanium": {
    dark: {
      accent: "#00b4ff",
      contrast: 60,
      fonts: {
        code: null,
        ui: null,
      },
      ink: "#e8ecf4",
      opaqueWindows: false,
      semanticColors: {
        diffAdded: "#00ff88",
        diffRemoved: "#ff4757",
        skill: "#00ff88",
      },
      surface: "#151820",
    },
  },
};
