#!/usr/bin/env node
/**
 * Generate the bundled skill payload for the oh-my-pi skills Peak Code ships in-tree.
 *
 * A pi skill on disk is `<id>/SKILL.md` (plus optional referenced files). The installed
 * server bundles TypeScript only, so the files are embedded here as strings and written to
 * the shared skill library at startup by `packages/agent-toolkit/src/skills/bundled.ts`.
 *
 * Usage:
 *   bun scripts/generate-oh-my-pi-bundled-skills.ts --source /path/to/oh-my-pi
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, posix, relative, resolve, sep } from "node:path";

import { gitHead, resolveOhMyPiSource, upstreamAttribution } from "./lib/oh-my-pi-source.ts";

const OUTPUT = resolve(
  import.meta.dirname,
  "..",
  "packages",
  "agent-toolkit",
  "src",
  "skills",
  "oh-my-pi.bundled.generated.ts",
);

/**
 * Skill directories ported verbatim. `tool-prompt-optimization` is intentionally absent:
 * its probe scripts import oh-my-pi's own `@oh-my-pi/pi-ai` and instantiate oh-my-pi tools,
 * so the Markdown would advertise files that are not in the payload.
 */
const SKILL_IDS = ["semantic-compression", "system-prompts"] as const;

function descriptionOf(skillMd: string): string {
  const match = /^description:\s*(.*)$/m.exec(skillMd);
  return (match?.[1] ?? "").trim().replace(/^["']|["']$/g, "");
}

/** Every file under a skill directory, as repo-relative POSIX paths. */
function filesOf(skillDir: string): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      if (entry.startsWith(".")) continue;
      const absolute = join(dir, entry);
      if (statSync(absolute).isDirectory()) walk(absolute);
      else {
        files.push({
          path: relative(skillDir, absolute).split(sep).join(posix.sep),
          content: readFileSync(absolute, "utf8"),
        });
      }
    }
  };
  walk(skillDir);
  return files.toSorted((a, b) => a.path.localeCompare(b.path));
}

function render(source: string, upstreamCommit: string): string {
  const skillsDir = join(source, ".omp", "skills");
  const skills = SKILL_IDS.map((id) => {
    const files = filesOf(join(skillsDir, id));
    const skillMd = files.find((file) => file.path === "SKILL.md")?.content ?? "";
    return { id, description: descriptionOf(skillMd), files };
  });

  const body = skills
    .map(
      (skill) => `  {
    id: ${JSON.stringify(skill.id)},
    description: ${JSON.stringify(skill.description)},
    files: [
${skill.files
  .map(
    (file) =>
      `      { path: ${JSON.stringify(file.path)}, content: ${JSON.stringify(file.content)} },`,
  )
  .join("\n")}
    ],
  },`,
    )
    .join("\n");

  return `// FILE: oh-my-pi.bundled.generated.ts
// Purpose: In-tree payload of the oh-my-pi skills Peak Code ships as bundled skills.
// Layer: Agent toolkit skills
// Generated by: scripts/generate-oh-my-pi-bundled-skills.ts --source <oh-my-pi checkout>
// Upstream: ${upstreamAttribution(upstreamCommit)}
// Exports: OH_MY_PI_BUNDLED_SKILLS for ./bundled.ts.

export interface BundledSkillFile {
  /** POSIX path relative to the skill directory, e.g. \`SKILL.md\` or \`scripts/probe.ts\`. */
  readonly path: string;
  readonly content: string;
}

export interface BundledSkill {
  readonly id: string;
  readonly description: string;
  readonly files: readonly BundledSkillFile[];
}

export const OH_MY_PI_BUNDLED_SKILLS: readonly BundledSkill[] = [
${body}
];
`;
}

const source = resolveOhMyPiSource(process.argv.slice(2));
writeFileSync(OUTPUT, render(source, gitHead(source)));
console.log(`wrote ${OUTPUT} (${SKILL_IDS.length} skills)`);
